apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: github-tests-go-dmywnxri
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/github-tests-go-dmywnxri:97ebe0e63c60d2e366e88311d33715219aa0401d
          name: container-image
